---
title: 'Brain specific genes analysis: Robocov'
author: "Kushal K. Dey and Alkes"
date: "6/9/2020"
output: html_document
---

```{r}
library(data.table)
library(ggplot2)
library(corrplot)
```

## Load data

We present here three examples of genes that have distinct characteristic patterns of tissue-wide correlations.

```{r}
robocov_gtex = get(load("/Users/kushaldey/Documents/Robocov-pages/data/Robocov_Box_all_genes.rda"))
probocov_gtex = get(load("/Users/kushaldey/Documents/Robocov-pages/data/Robocov_Precision_all_genes.rda"))
robospan = apply(robocov_gtex, 3, sum)/(53*53)
```

### PAX6

```{r fig.height=8, fig.width=8}
corrplot(robocov_gtex[,,"ENSG00000132639"],   diag = TRUE,
         col = colorRampPalette(c("lightblue4", "lightblue2", "white", "indianred1", "indianred3"))(200),
         tl.pos = "ld", tl.cex = 0.6, tl.col = "black",
         rect.col = "white",na.label.col = "white",
         method = "color", type = "lower", tl.srt=45)
```


```{r}
brain_gtex = robocov_gtex[8:20, 8:20, ]
nonbrain_gtex = robocov_gtex[-(8:20), -(8:20), ]
tt = apply(brain_gtex, 3, median) - apply(nonbrain_gtex, 3, median)
```


```{r}

```




