---
title: "Supplementary Examples different structures"
author: "Kushal K. Dey and Rahul Mazumder"
date: "11/28/2019"
output: html_document
---

```{r}
library(corrplot)
```

```{r}
robocov_gtex = get(load("/Users/kushaldey/Documents/Robocov-pages/data/Robocov_Box_all_genes.rda"))
dim(robocov_gtex)
```

```{r}
robospan = apply(robocov_gtex, 3, sum)/(53*53)
plot(density(robospan), xlab = "Robospan score", ylab = "density")
```

```{r}
robospan[order(robospan, decreasing = T)[1:10]]
```

```{r}
robospan[order(robospan, decreasing = F)[1:20]]
```

```{r fig.height=10, fig.width=10}
corrplot(robocov_gtex[,,"ENSG00000242571"],  diag = TRUE,
         col = colorRampPalette(c("lightblue4", "lightblue2", "white", "indianred1", "indianred3"))(200),
         tl.pos = "ld", tl.cex = 0.8, tl.col = "black",
         rect.col = "white",na.label.col = "white",
         method = "color", type = "lower", tl.srt=45)
```

```{r fig.height=10, fig.width=10}
corrplot(robocov_gtex[,,"ENSG00000134184"],  diag = TRUE,
         col = colorRampPalette(c("lightblue4", "lightblue2", "white", "indianred1", "indianred3"))(200),
         tl.pos = "ld", tl.cex = 0.8, tl.col = "black",
         rect.col = "white",na.label.col = "white",
         method = "color", type = "lower", tl.srt=45)
```

```{r}
robospan[order(robospan, decreasing = T)[1:50]]
```

```{r fig.height=10, fig.width=10}
corrplot(robocov_gtex[,,"ENSG00000179344"],  diag = TRUE,
         col = colorRampPalette(c("lightblue4", "lightblue2", "white", "indianred1", "indianred3"))(200),
         tl.pos = "ld", tl.cex = 0.8, tl.col = "black",
         rect.col = "white",na.label.col = "white",
         method = "color", type = "lower", tl.srt=45)
```

```{r fig.height=10, fig.width=10}
corrplot(robocov_gtex[,,"ENSG00000214425"],  diag = TRUE,
         col = colorRampPalette(c("lightblue4", "lightblue2", "white", "indianred1", "indianred3"))(200),
         tl.pos = "ld", tl.cex = 0.8, tl.col = "black",
         rect.col = "white",na.label.col = "white",
         method = "color", type = "lower", tl.srt=45)
```

```{r fig.height=10, fig.width=10}
corrplot(robocov_gtex[,,"ENSG00000011600"],  diag = TRUE,
         col = colorRampPalette(c("lightblue4", "lightblue2", "white", "indianred1", "indianred3"))(200),
         tl.pos = "ld", tl.cex = 0.8, tl.col = "black",
         rect.col = "white",na.label.col = "white",
         method = "color", type = "lower", tl.srt=45)
```

```{r fig.height=10, fig.width=10}
corrplot(robocov_gtex[,,"ENSG00000015475"],  diag = TRUE,
         col = colorRampPalette(c("lightblue4", "lightblue2", "white", "indianred1", "indianred3"))(200),
         tl.pos = "ld", tl.cex = 0.8, tl.col = "black",
         rect.col = "white",na.label.col = "white",
         method = "color", type = "lower", tl.srt=45)
```

