---
title: "Predictive accuracy of Robocov"
author: "Kushal K Dey, Bryce Van de Geijn, Alkes Price"
date: "9/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The CorShrink-sparse version assumes a box constraint on the correlation estimates $\hat{R}_{ij}$. Now this box constraint is essentially a probabilistic statement which is why we imposed a relaxation in the form of introducing slack variables. We call this version `CorShrink-sparse-slack`.

```{r}
library(corrplot)
library(CVXR)
library(ggplot2)
library(CorShrink)
library(Robocov)
```

## PLIN1 gene results

```{r}
data("sample_by_feature_data")
data("common_samples")
dim(sample_by_feature_data)

nloglik = function(data, cormat){
  llik = 0
  for(m in 1:nrow(data)){
    idx = which(!is.na(data[m,]))
    if(length(idx) > 2){
      llik = llik + emdbook::dmvnorm(data[m, idx], rep(0, length(idx)), cormat[idx, idx], log = T)
    }
  }
  return(-llik)
}

```

```{r}
measure = c()
measure2 = c()
for(num_iter in 1:5){
  train_sample_id = sample(1:nrow(sample_by_feature_data), 300, replace = FALSE)
  predict_sample_id = setdiff(1:nrow(sample_by_feature_data), train_sample_id)
  train_datamat = sample_by_feature_data[train_sample_id,]
  
  empirical_cor = cor(train_datamat, method = "pearson", use = "pairwise.complete.obs")
  empirical_cor[is.na(empirical_cor)] = 0
  
  corshrink_out = CorShrinkData(train_datamat, sd_boot = FALSE, image = "null",
                                image.control = list(tl.cex = 0.2))
  corshrink_cor = corshrink_out$cor
  
  robocov_box_cor = Robocov_box(data_with_missing = train_datamat)
  
  alpha_vec = c(1e-02, 0.05, 0.1, 0.5, 1, 5, 10, 50, 100)
  nlik_list = rep(0, length(alpha_vec))
  for(m in 1:length(alpha_vec)){
    temp_cor = Robocov_box_slack( train_datamat, alpha=alpha_vec[m])
    nlik_list[m] = nloglik( train_datamat, as.matrix(nearPD(temp_cor)$mat))
    cat("Passed alpha value: ", alpha_vec[m], "\n")
  }
  final_alpha = alpha_vec[which.min(nlik_list)]
  robocov_box_slack_cor =  Robocov_box_slack(train_datamat, alpha=final_alpha)
  
  robocov_local_cor =  Robocov_local(train_datamat, alpha=5)
  
  predict_datamat = sample_by_feature_data[predict_sample_id,]
  cormat2 = cor(predict_datamat, method = "pearson", use = "pairwise.complete.obs")
  cormat2[is.na(cormat2)] = 0
  measure = rbind(measure, c(mean(abs(cormat2 - empirical_cor)),
                             mean(abs(cormat2 - corshrink_cor)),
                             mean(abs(cormat2 - robocov_box_cor)),
                             mean(abs(cormat2 - robocov_box_slack_cor)),
                             mean(abs(cormat2 - robocov_local_cor)))
                      )
  measure2 = rbind(measure2, c(sqrt(mean((cormat2 - empirical_cor)^2)),
                             sqrt(mean((cormat2 - corshrink_cor)^2)),
                             sqrt(mean((cormat2 - robocov_box_cor)^2)),
                             sqrt(mean((cormat2 - robocov_box_slack_cor)^2)),
                             sqrt(mean((cormat2 - robocov_local_cor)^2))))
  cat("We finished iteration:", num_iter)
}

```

```{r}
measure
```

```{r}
measure2
```

```{r}
cbind(colMeans(measure), colMeans(measure2))
```

```{r}
cbind(apply(measure, 2, sd), apply(measure2, 2, sd))
```
