---
title: "GTEx pRobocov demo and pRobospan"
author: "Kushal K. Dey and Alkes Price"
date: "11/23/2019"
output: html_document
---

```{r}
library(Robocov)
library(corrplot)
library(ggplot2)
```

Here we illustrare the Robocov estimates for a few genes of interest and then introduce the concept of Robospan.

```{r}
probocov_gtex = get(load("/Users/kushaldey/Documents/Robocov-pages/data/Robocov_Precision_all_genes.rda"))
robocov_gtex = get(load("/Users/kushaldey/Documents/Robocov-pages/data/Robocov_Box_all_genes.rda"))
dim(probocov_gtex)
```

## HBB (ENSG00000244734)

```{r}
corrplot(probocov_gtex[,,"ENSG00000244734"],  diag = TRUE,
         col = colorRampPalette(c("blue", "white", "red"))(200),
         tl.pos = "td", tl.cex = 0.4, tl.col = "black",
         rect.col = "white",na.label.col = "white",
         method = "color", type = "upper")
```


```{r}
probospan = apply(probocov_gtex, 3, sum)/(53*53)
plot(density(probospan), xlab = "Robospan score", ylab = "density")
```

```{r}
probospan[order(probospan, decreasing = T)[1:10]]
```

```{r}
corrplot(probocov_gtex[,,"ENSG00000237039"],  diag = TRUE,
         col = colorRampPalette(c("blue", "white", "red"))(200),
         tl.pos = "td", tl.cex = 0.4, tl.col = "black",
         rect.col = "white",na.label.col = "white",
         method = "color", type = "upper")

corrplot(robocov_gtex[,,"ENSG00000237039"],  diag = TRUE,
         col = colorRampPalette(c("blue", "white", "red"))(200),
         tl.pos = "td", tl.cex = 0.4, tl.col = "black",
         rect.col = "white",na.label.col = "white",
         method = "color", type = "upper")
```


Ensembl and Gene symbol names 

```{r}
ensembl_gene_symbol = read.table("/Users/kushaldey/Documents/Robocov-pages/data/Gene_Scores/ensembl_and_hgnc_symbols.txt")
head(ensembl_gene_symbol)
```

```{r}
gene_symbols = ensembl_gene_symbol[match(names(probospan), ensembl_gene_symbol[,1]), 2]
probospan2 = probospan[which(!is.na(gene_symbols))] 
names(probospan2) = gene_symbols[which(!is.na(gene_symbols))]
```

## pRobospan mean 

```{r}
genes = names(probospan2)[order(probospan2, decreasing = T)[1:1600]]
df = cbind.data.frame(genes, 1)
write.table(df, file = "/Users/kushaldey/Documents/Robocov-pages/data/Gene_Scores/pRobospan_mean.txt",
            row.names = F, col.names = F, sep = "\t", quote=F)
```

## pRobospan mean Blood 

```{r}
probospan = apply(probocov_gtex[,53,], 2, mean)
gene_symbols = ensembl_gene_symbol[match(names(probospan), ensembl_gene_symbol[,1]), 2]
probospan2 = probospan[which(!is.na(gene_symbols))] 
names(probospan2) = gene_symbols[which(!is.na(gene_symbols))]
genes = names(probospan2)[order(probospan2, decreasing = T)[1:1600]]
df = cbind.data.frame(genes, 1)
write.table(df, file = "/Users/kushaldey/Documents/Robocov-pages/data/Gene_Scores/pRobospan_Mean_Blood.txt",
            row.names = F, col.names = F, sep = "\t", quote=F)
```





