---
title: "Robocov data analysis"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
---

This is the repository webpage for reproducing the analysis presented in the Robocov paper (Dey and Mazumder 2020).

## Simulation experiments

- [Application of Robocov on Hub network models](hub_robocov.html)

- [Application of Robocov on Toeplitz network models](toeplitz_robocov.html)

- [Application of Robocov on 1-band precision matrix network models](band_prec_robocov.html)

## GTEx analysis 

- [Basic exploration of Robocov estimators using GTEx data](gtex_analysis_robocov_examples.html)

- [Mean and Median Robocov patterns across tissue pairs over all genes](mean_robocov.html)

- [Predictive analytics comparison of Robocov and CorShrink with standard approach for a GTEx gene](predictive_analytics_gtex.html)

- [Different patterns of Robocov correlation in GTEx data](diff_robospan_examples.html)

- [Comapring imputation methods to Robocov for GTEx gene expression data](gtex_rank_imputation.html)

- [How to compute Robospan score from Robocov correlation estimator of GTEx expression data across genes](gtex_robocov_ex_robospan.html)

- [How to compute pRobospan score from Robocov partial correlationestimator of GTEx expression data across genes](gtex_pRobocov_pRobospan.html)

## Robospan, pRobospan and Corspan gene sets 

- [Enrichment of Corspan, Robospan and pRobospan gene sets in housekeeping genes and SEG-Blood](SEG_housekeeping_enrich.html)

- [S-LDSC results for Corspan, Robospan and pRobospan scores](corspan_robospan_probospan.html)
