---
title: "NMF Robocov examples"
author: "Kushal K. Dey and Alkes"
date: "6/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=F, message=F}
library(corrplot)
library(ggplot2)
```


## Robocov

```{r}
robocov_gtex = get(load("/Users/kushaldey/Documents/Robocov-pages/data/Robocov_Box_all_genes.rda"))
```

```{r fig.height=8, fig.width=8}
genes_vec = c()
for(qq in 1:5){
  genes = as.character(read.table(paste0("~/Documents/Robocov-pages/output/NMF_run_5_robocov/NMF_run_5_clus_",
              qq, ".txt"), header=F)[,1])
  matt2 = robocov_gtex[,,genes]
  matt3 = apply(matt2, c(1,2), mean)
  corrplot(matt3,   diag = TRUE,
           col = colorRampPalette(c("lightblue4", "lightblue2", "white", "indianred1", "indianred3"))(200),
           tl.pos = "ld", tl.cex = 0.6, tl.col = "black",
           rect.col = "white",na.label.col = "white",
           method = "color", type = "lower", tl.srt=45)
  genes_vec = c(genes_vec, length(genes))
}
```

```{r}
genes_vec
```


## Robocov precision

```{r}
robocov_gtex = get(load("/Users/kushaldey/Documents/Robocov-pages/data/Robocov_Precision_all_genes.rda"))
```

```{r fig.height=8, fig.width=8}
genes_vec = c()
for(qq in 1:5){
  genes = as.character(read.table(paste0("~/Documents/Robocov-pages/output/NMF_run_5_probocov/NMF_run_5_clus_",
              qq, ".txt"), header=F)[,1])
  matt2 = robocov_gtex[,,genes]
  matt3 = apply(matt2, c(1,2), mean)
  corrplot(matt3,   diag = TRUE,
           col = colorRampPalette(c("lightblue4", "lightblue2", "white", "indianred1", "indianred3"))(200),
           tl.pos = "ld", tl.cex = 0.6, tl.col = "black",
           rect.col = "white",na.label.col = "white",
           method = "color", type = "lower", tl.srt=45)
  genes_vec = c(genes_vec, length(genes))
}
```

```{r}
genes_vec
```

## Standard

```{r}
robocov_gtex = get(load("/Users/kushaldey/Documents/Robocov-pages/data/Cor_pairwise_all_genes.rda"))
```

```{r fig.height=8, fig.width=8}
genes_vec = c()
for(qq in 1:5){
  genes = as.character(read.table(paste0("~/Documents/Robocov-pages/output/NMF_run_5_standard/NMF_run_5_clus_",
              qq, ".txt"), header=F)[,1])
  matt2 = robocov_gtex[,,genes]
  matt3 = apply(matt2, c(1,2), mean)
  corrplot(matt3,   diag = TRUE,
           col = colorRampPalette(c("lightblue4", "lightblue2", "white", "indianred1", "indianred3"))(200),
           tl.pos = "ld", tl.cex = 0.6, tl.col = "black",
           rect.col = "white",na.label.col = "white",
           method = "color", type = "lower", tl.srt=45)
  genes_vec = c(genes_vec, length(genes))
}
```

```{r}
genes_vec
```

