---
title: "Predictive analytics for GTEx genes"
author: "Kushal K. Dey and Rahul Mazumder"
date: "11/26/2019"
output: html_document
---

```{r setup, include=FALSE}
library("knitr")
library(kableExtra)
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=F, message=F}
library(corrplot)
opts_chunk$set(tidy=FALSE,tidy.opts=list(width.cutoff=30),dev="png",
               fig.width=9,fig.height=9,
               message=FALSE, warning = FALSE)
```

## Predictive analytics for different GTEx genes 

```{r}
library(corrplot)
library(CVXR)
library(ggplot2)
library(CorShrink)
library(Robocov)
```

```{r}
nloglik = function(data, cormat){
  llik = 0
  for(m in 1:nrow(data)){
    idx = which(!is.na(data[m,]))
    if(length(idx) > 2){
      llik = llik + emdbook::dmvnorm(data[m, idx], rep(0, length(idx)), cormat[idx, idx], log = T)
    }
  }
  return(-llik)
}

```



```{r}
all_data = get(load("/Users/kushaldey/Documents/Robocov-pages/data/person_tissue_genes_voom.rda"))
```

```{r}
#samples = sample(1:dim(all_data)[3], 1)
samples = 10498 ## a random gene index (can be any value from 1 to 16,069)
measure = c()
measure2 = c()
for(ss in samples){
  gene_data = all_data[,,ss]
  for(num_iter in 1:5){
    train_sample_id = sample(1:nrow(gene_data), floor(nrow(gene_data)/2), replace = FALSE)
    predict_sample_id = setdiff(1:nrow(gene_data), train_sample_id)
    train_datamat = gene_data[train_sample_id,]
    
    empirical_cor = cor(train_datamat, method = "pearson", use = "pairwise.complete.obs")
    empirical_cor[is.na(empirical_cor)] = 0
    
    corshrink_out = CorShrinkData(train_datamat, sd_boot = FALSE, image = "null",
                                  image.control = list(tl.cex = 0.2))
    corshrink_cor = corshrink_out$cor
    
    robocov_box_cor = Robocov_cor(data_with_missing = train_datamat, loss = "lasso")
    
    predict_datamat = gene_data[predict_sample_id,]
    cormat2 = cor(predict_datamat, method = "pearson", use = "pairwise.complete.obs")
    cormat2[is.na(cormat2)] = 0
    measure = rbind(measure, c(mean(abs(cormat2 - empirical_cor)),
                               mean(abs(cormat2 - corshrink_cor)),
                               mean(abs(cormat2 - robocov_box_cor)))
                        )
    measure2 = rbind(measure2, c(sqrt(mean((cormat2 - empirical_cor)^2)),
                               sqrt(mean((cormat2 - corshrink_cor)^2)),
                               sqrt(mean((cormat2 - robocov_box_cor)^2))))
    cat("We finished iteration:", num_iter)
  }
  cat("We have finished analysis for gene:", ss, "\n")
}

```

```{r fig.height=10, fig.width=10}
robocov_all_genes = get(load("/Users/kushaldey/Documents/Robocov-pages/data/Robocov_Box_all_genes.rda"))
corrplot(robocov_all_genes[,,samples],   diag = TRUE,
         col = colorRampPalette(c("lightblue4", "lightblue2", "white", "indianred1", "indianred3"))(200),
         tl.pos = "ld", tl.cex = 0.8, tl.col = "black",
         rect.col = "white",na.label.col = "white",
         method = "color", type = "lower", tl.srt=45)
```


```{r}
df = data.frame ("tau" = c(measure[,1], measure[,2], measure[,3]),
                 "x" = factor(c(rep("Sample-est",5), rep("CorShrink",5), rep("Robocov",5)),
                         levels = c("Sample-est", "CorShrink", "Robocov")))
p <- ggplot(df, aes(x=x, y=tau, fill=x)) +
  geom_boxplot(position = "identity", stat = "boxplot") +
  theme(axis.text.x = element_text(angle = 70, hjust = 1, size = 50), legend.position="top") +
  ggtitle(paste0("Mean Absolute Deviation for gene:", dimnames(robocov_all_genes)[[3]][samples]))  + 
  ylab("MAD") +
  theme_bw()
p
```

```{r}
df = data.frame ("tau" = c(measure2[,1], measure2[,2], measure2[,3]),
                 "x" = factor(c(rep("Sample-est",5), rep("CorShrink",5), rep("Robocov",5)),
                         levels = c("Sample-est", "CorShrink", "Robocov")))
p <- ggplot(df, aes(x=x, y=tau, fill=x)) +
  geom_boxplot(position = "identity", stat = "boxplot") +
  theme(axis.text.x = element_text(angle = 70, hjust = 1, size = 50), legend.position="top") +
  ggtitle(paste0("RMSE for gene:", dimnames(robocov_all_genes)[[3]][samples]))  + 
  ylab("RMSE") +
  theme_bw()
p
```


```{r}
apply(measure, 2, mean)
apply(measure, 2, sd)
apply(measure2, 2, mean)
apply(measure2, 2, sd)
```

